name: Run Tests and Generate Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      ALUMNIUM_MODEL: ${{ vars.ALUMNIUM_MODEL }}
      ALLURE_RESULTS_DIR: allure-results
      ALLURE_REPORT_DIR: allure-report

    steps:
      - name: Check ENV
        run: |
          echo $ALUMNIUM_MODEL
          echo $GOOGLE_API_KEY

      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg curl unzip
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps
          sudo apt-get install xvfb

      - name: Start virtual display I
        run: |
          export DISPLAY=:99

      - name: Start virtual display II
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Start virtual display III
        run: |          
          echo $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Copy previous history (if exists)
        run: |
          mkdir -p allure-report/history
          if git show origin/gh-pages:history > /dev/null 2>&1; then
            git fetch
            git checkout origin/gh-pages -- history
            cp -r history/ allure-results/history || true
          fi

      - name: 🚀 Run Behave Tests with Allure
        run: |
          rm -rf $ALLURE_RESULTS_DIR $ALLURE_REPORT_DIR
          behave -f allure_behave.formatter:AllureFormatter -o $ALLURE_RESULTS_DIR

      - name: 🧾 Generate Allure Report
        if: always()
        run: |
          npm install -g allure-commandline --save-dev
          allure generate $ALLURE_RESULTS_DIR -o $ALLURE_REPORT_DIR --clean

      - name: 📤 Upload Allure Report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: 📤 Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          keep_files: false
            
      - name: 🧪 Upload Playwright Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: artifacts

      - name: 📦 Upload Raw Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
